# -*- coding: utf-8 -*-
"""convert_coco_to_yolo.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tPQ-v9hjIHCqxmDZ52kiA7Cn_FXD8BrH
"""

#!/usr/bin/env python3
"""
Convert COCO annotations to YOLO format.

This script reads a COCO JSON file, copies the corresponding images, and creates
YOLO .txt label files. It supports:
- Mapping all non‑debris categories to class 0 and a specified debris category to class 1.
- Optionally creating a balanced subset with equal numbers of debris and non‑debris images.
- Random sampling with a fixed seed for reproducibility.
"""

import os
import json
import random
import shutil
import argparse
from collections import defaultdict

def parse_args():
    parser = argparse.ArgumentParser(description="Convert COCO annotations to YOLO format.")
    parser.add_argument("--coco_json", required=True, help="Path to COCO JSON file (e.g., instances_train.json).")
    parser.add_argument("--img_dir", required=True, help="Directory containing the images referenced in the JSON.")
    parser.add_argument("--output_dir", required=True, help="Output directory for YOLO dataset (images/ and labels/ subfolders).")
    parser.add_argument("--split", default="train", help="Split name (e.g., train, val, test). Will create images/{split} and labels/{split}.")
    parser.add_argument("--debris_names", nargs="+", default=["spacedebris", "spacerock"], help="Category names to treat as debris (class 1). All others become class 0.")
    parser.add_argument("--subset_size", type=int, default=None, help="Total number of images to sample (if not None).")
    parser.add_argument("--balance", action="store_true", help="If True, balance the subset by taking equal numbers of debris and non‑debris images.")
    parser.add_argument("--seed", type=int, default=42, help="Random seed for reproducibility.")
    return parser.parse_args()

def main():
    args = parse_args()

    # Set random seed
    random.seed(args.seed)

    # Load COCO data
    with open(args.coco_json, "r") as f:
        coco = json.load(f)

    # Build category mapping
    cat_id_to_name = {cat["id"]: cat["name"] for cat in coco["categories"]}
    debris_cat_ids = [cid for cid, name in cat_id_to_name.items() if name in args.debris_names]
    if not debris_cat_ids:
        raise ValueError(f"None of the debris names {args.debris_names} found in categories.")
    debris_cat_ids_set = set(debris_cat_ids)

    # All other categories become class 0, debris become class 1
    class_map = {cid: 0 for cid in cat_id_to_name}
    for cid in debris_cat_ids:
        class_map[cid] = 1

    # Build mapping from image id to image info
    img_id_to_info = {img["id"]: img for img in coco["images"]}

    # Group annotations by image id
    anns_by_img = defaultdict(list)
    for ann in coco["annotations"]:
        # skip crowd annotations
        if ann.get("iscrowd", 0) == 1:
            continue
        anns_by_img[ann["image_id"]].append(ann)

    # Determine which images contain debris
    debris_img_ids = set()
    non_debris_img_ids = set()
    for img_id, anns in anns_by_img.items():
        if any(class_map[ann["category_id"]] == 1 for ann in anns):
            debris_img_ids.add(img_id)
        else:
            non_debris_img_ids.add(img_id)

    print(f"Total images: {len(img_id_to_info)}")
    print(f"Images with debris: {len(debris_img_ids)}")
    print(f"Images without debris: {len(non_debris_img_ids)}")

    # Sample subset if requested
    if args.subset_size is not None:
        if args.balance:
            # Sample equal numbers from debris and non‑debris
            n_each = args.subset_size // 2
            if n_each == 0:
                raise ValueError("subset_size too small for balanced sampling.")
            n_debris = min(n_each, len(debris_img_ids))
            n_non = min(n_each, len(non_debris_img_ids))
            # If one class is too small, we'll still try to get as many as possible
            sampled_debris = random.sample(list(debris_img_ids), n_debris) if n_debris > 0 else []
            sampled_non = random.sample(list(non_debris_img_ids), n_non) if n_non > 0 else []
            selected_img_ids = sampled_debris + sampled_non
            print(f"Balanced sampling: {len(sampled_debris)} debris, {len(sampled_non)} non‑debris images.")
        else:
            # Simple random sampling from all images
            selected_img_ids = random.sample(list(img_id_to_info.keys()), min(args.subset_size, len(img_id_to_info)))
            print(f"Random sampling: {len(selected_img_ids)} images selected.")
    else:
        # Use all images
        selected_img_ids = list(img_id_to_info.keys())
        print(f"Using all {len(selected_img_ids)} images.")

    # Create output directories
    img_out_dir = os.path.join(args.output_dir, "images", args.split)
    lbl_out_dir = os.path.join(args.output_dir, "labels", args.split)
    os.makedirs(img_out_dir, exist_ok=True)
    os.makedirs(lbl_out_dir, exist_ok=True)

    # Convert each selected image
    for img_id in selected_img_ids:
        img_info = img_id_to_info[img_id]
        src_img = os.path.join(args.img_dir, img_info["file_name"])
        dst_img = os.path.join(img_out_dir, img_info["file_name"])
        if not os.path.exists(src_img):
            print(f"Warning: Image {src_img} not found, skipping.")
            continue
        shutil.copy2(src_img, dst_img)

        # Write YOLO labels
        anns = anns_by_img.get(img_id, [])
        txt_file = os.path.splitext(img_info["file_name"])[0] + ".txt"
        txt_path = os.path.join(lbl_out_dir, txt_file)
        with open(txt_path, "w") as f:
            for ann in anns:
                cls = class_map[ann["category_id"]]
                bbox = ann["bbox"]  # [x, y, width, height] (top-left)
                x, y, w, h = bbox
                # Normalize to [0,1]
                x_center = (x + w/2) / img_info["width"]
                y_center = (y + h/2) / img_info["height"]
                norm_w = w / img_info["width"]
                norm_h = h / img_info["height"]
                f.write(f"{cls} {x_center:.6f} {y_center:.6f} {norm_w:.6f} {norm_h:.6f}\n")

    print(f"Done. Converted {len(selected_img_ids)} images to YOLO format in {args.output_dir}")

if __name__ == "__main__":
    main()