# -*- coding: utf-8 -*-
"""train.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tPQ-v9hjIHCqxmDZ52kiA7Cn_FXD8BrH
"""

#!/usr/bin/env python3
"""
Train a YOLO model on the prepared debris dataset.

This script supports:
- Starting fresh training from a pretrained YOLO model.
- Resuming from a previous checkpoint.
- Customising all training hyperparameters.
- Applying class weights to handle imbalance (defaults: non‑debris=0.7147, debris=1.6646).
- Automatically generating a unique experiment name.

Usage examples:
    python train.py --data /content/balanced_dataset.yaml --epochs 50
    python train.py --data data.yaml --resume runs/detect/experiment/weights/last.pt
    python train.py --data data.yaml --class_weights 0.5 1.5   # custom weights
    python train.py --data data.yaml --no_class_weights       # equal weights
"""

import os
import argparse
from datetime import datetime
import random
import numpy as np
from ultralytics import YOLO

def parse_args():
    parser = argparse.ArgumentParser(description="Train YOLO model for debris detection.")
    parser.add_argument("--data", required=True, help="Path to dataset YAML file.")
    parser.add_argument("--model", default="yolo11n.pt", help="Pretrained model file (or name).")
    parser.add_argument("--resume", default=None, help="Path to a previous experiment folder (or last.pt) to resume training.")
    parser.add_argument("--epochs", type=int, default=50, help="Number of training epochs.")
    parser.add_argument("--imgsz", type=int, default=640, help="Input image size.")
    parser.add_argument("--batch", type=int, default=16, help="Batch size.")
    parser.add_argument("--workers", type=int, default=4, help="Number of dataloader workers.")
    parser.add_argument("--patience", type=int, default=10, help="Early stopping patience (epochs).")
    parser.add_argument("--save_period", type=int, default=1, help="Save checkpoint every N epochs.")
    parser.add_argument("--project", default="/content/drive/MyDrive/space_debris_runs", help="Root directory for experiment logs.")
    parser.add_argument("--name", default=None, help="Experiment name. If None, a timestamp is used.")
    parser.add_argument("--freeze", type=int, default=22, help="Number of layers to freeze (backbone).")
    parser.add_argument("--exist_ok", action="store_true", help="If set, allow overwriting an existing experiment folder.")
    parser.add_argument("--seed", type=int, default=42, help="Random seed for reproducibility.")

    # Class weights
    parser.add_argument("--class_weights", nargs=2, type=float, default=[0.7147, 1.6646],
                        help="Class weights for [non_debris, debris] (e.g., --class_weights 0.5 1.5). "
                             "Default: 0.7147 1.6646 (recommended from dataset analysis).")
    parser.add_argument("--no_class_weights", action="store_true",
                        help="If set, do NOT apply class weights (use equal weights).")
    return parser.parse_args()

def main():
    args = parse_args()

    # Set random seeds for reproducibility
    random.seed(args.seed)
    np.random.seed(args.seed)

    # Create experiment name if not provided
    if args.name is None:
        exp_name = f"debris_balanced_{datetime.now().strftime('%Y%m%d_%H%M')}"
    else:
        exp_name = args.name
    print(f"Experiment name: {exp_name}")

    # Determine model to load
    if args.resume:
        if os.path.isdir(args.resume):
            resume_ckpt = os.path.join(args.resume, "weights", "last.pt")
        else:
            resume_ckpt = args.resume
        if not os.path.exists(resume_ckpt):
            raise FileNotFoundError(f"Checkpoint not found: {resume_ckpt}")
        model = YOLO(resume_ckpt)
        print(f"Resuming training from {resume_ckpt}")
    else:
        model = YOLO(args.model)
        print("Starting fresh training")

    # Prepare training arguments
    train_kwargs = {
        "data": args.data,
        "epochs": args.epochs,
        "imgsz": args.imgsz,
        "batch": args.batch,
        "workers": args.workers,
        "patience": args.patience,
        "save_period": args.save_period,
        "project": args.project,
        "name": exp_name,
        "exist_ok": args.exist_ok,
        "resume": bool(args.resume),
        "freeze": args.freeze,
    }

    # Apply class weights unless --no_class_weights is set
    if not args.no_class_weights:
        train_kwargs["class_weights"] = args.class_weights
        print(f"Using class weights: non_debris={args.class_weights[0]}, debris={args.class_weights[1]}")
    else:
        print("Using equal class weights (no balancing).")

    # Train
    results = model.train(**train_kwargs)

    print("Training completed.")
    print(f"Best model saved to: {os.path.join(args.project, exp_name, 'weights', 'best.pt')}")

if __name__ == "__main__":
    main()